
FROM python:3.7-slim

RUN mkdir /app

COPY ./requirements.txt /app

RUN pip3 install -r /app/requirements.txt --no-cache-dir

COPY api_yamdb/ /app

CMD ["gunicorn", "api_yamdb.wsgi", "--bind", "0:8000"]
